#!/usr/bin/env bash
# script which transfers files to a server





if [ "$#" -ne 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi




scp -o -q StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i "$4" "$1" "$3@$2":~/ 
