#!/usr/bin/env bash
# scripted configuring Nginx
# 0-custom_http_response_header was wrttrn to configure a brand new unbutu


apt-get update -y
apt-get install nginx -y
echo "Hello World!" > /usr/share/nginx/html/index.html
mkdir -p /var/www/html
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html
sudo sed -i -E "s/^[^#]+location \/ \{/$new_string/" /etc/nginx/sites-available/default
sudo sed -i -E "s/^server \{/$new_string2/" /etc/nginx/sites-available/default
sudo service nginx start
