#!/usr/bin/env bash
# HAproxy configuration to meet yp eorh web-02
# request was distributed using roundrobin algorithm
# HAproxy can be managed via an init script
# servers are configured with the right hostnames


apt-get update
apt-get -y install haproxy
echo "ENABLED=1" >> /etc/default/haproxy
sed -i '/504.http/a \\nlisten http-in\n\tbind *:80\n\tmode http\n\tbalance roundrobin\n\tserver 1231-web-01 34.74.70.205:80 check\n\tserver 1231-web-02 34.224.30.177:80 check' /etc/haproxy/haproxy.cfg


sudo service haproxy start
