#!/usr/bin/env bash
# this is the script that displays numbers from 1 to 100
v="1"

while [ $v -lt 101 ]
do
	if [ $((v%15)) = 0 ]
	then
		echo "FizzBuzz"
	elif [ $((v%3)) = 0 ]
	then
		echo "Fizz"
	elif [ $((v%5)) = 0 ]
	then
		echo "Buzz"
	else
		echo "$v"
	fi
	v=$((v+1))
done
