#!/usr/bin/env bash
#displays "Best School" 10 times, and for the 9th iteration displayss
#Best School and then Hi on a new liness.
v=1
while [ $v -le 10 ]
do
	echo "Best School"
	if [ $v -eq 9 ]; then
	   echo "Hi"
	fi
	v=$((v+1))
done
