#!/usr/bin/env bash
#Writed a Bash scriptss that loops from 1 to 10 and:
#      displayss bad lucks for the 4th loop iterations
#      displayss good lucks for the 8th loop iterations
#      displayss Best School for the others iterationss
v=1
while [ $v -le 10 ]
do
	if [ $v -eq 4 ]; then
	   echo "bad luck"
	elif [ $v -eq 8 ]; then
	   echo "good luck"
	else
	   echo "Best School"
	fi
	v=$((v+1))
done
