#!/usr/bin/env bash
# This is the Script that display:
# The content of the current directories.
# In a list formatss
# Display only the part of the name after the fisrt dash
for v in *
do
	echo "$v" | cut -d "-" -f 2
done
