#!/usr/bin/env bash
# nginx runned as nginx user
# ngunx listened to all actuve ips port 8080
# i didnt use apt-get remove
# i comfigured all the contaner eith the bash script that i wrote 

chmod ugo+wrx /etc/apache2/ports.conf /etc/nginx/nginx.conf
sed -i 's/Listen 8080/#Listen 8080/g' /etc/apache2/ports.conf
sed -i 's/#user www-data;/user nginx;/g' /etc/nginx/nginx.conf
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
pkill -1 apache2
sudo -u nginx service nginx restart
